// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "API VEHICULOS",
    "version": "1",
    "description": "Esta API esta desarrollado con Serverless Framework en NodeJs y desplegado en AWS"
  },
  "paths": {
    "/vehiculo/": {
      "get": {
        "summary": "getAllVehiculos",
        "description": "",
        "operationId": "getAllVehiculos.get.vehiculo/",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/vehiculo": {
      "post": {
        "summary": "createVehiculo",
        "description": "",
        "operationId": "createVehiculo.post.vehiculo",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/vehiculoSwapi/": {
      "get": {
        "summary": "getAllVehiculosSwapi",
        "description": "",
        "operationId": "getAllVehiculosSwapi.get.vehiculoSwapi/",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "VehiculoEsResponse": {
      "properties": {
        "nombre": {
          "title": "VehiculoEsResponse.nombre",
          "type": "string"
        },
        "modelo": {
          "title": "VehiculoEsResponse.modelo",
          "type": "string"
        },
        "creado": {
          "title": "VehiculoEsResponse.creado",
          "type": "string"
        },
        "editado": {
          "title": "VehiculoEsResponse.editado",
          "type": "string"
        },
        "url": {
          "title": "VehiculoEsResponse.url",
          "type": "string"
        }
      },
      "required": [
        "nombre",
        "modelo",
        "creado",
        "editado",
        "url"
      ],
      "additionalProperties": false,
      "title": "VehiculoEsResponse",
      "type": "object"
    },
    "VehiculoResponse": {
      "properties": {
        "name": {
          "title": "VehiculoResponse.name",
          "type": "string"
        },
        "model": {
          "title": "VehiculoResponse.model",
          "type": "string"
        },
        "created": {
          "title": "VehiculoResponse.created",
          "type": "string"
        },
        "edited": {
          "title": "VehiculoResponse.edited",
          "type": "string"
        },
        "url": {
          "title": "VehiculoResponse.url",
          "type": "string"
        }
      },
      "required": [
        "name",
        "model",
        "created",
        "edited",
        "url"
      ],
      "additionalProperties": false,
      "title": "VehiculoResponse",
      "type": "object"
    },
    "Vehiculo": {
      "properties": {
        "todosId": {
          "title": "Vehiculo.todosId",
          "type": "string"
        },
        "title": {
          "title": "Vehiculo.title",
          "type": "string"
        },
        "description": {
          "title": "Vehiculo.description",
          "type": "string"
        },
        "status": {
          "title": "Vehiculo.status",
          "type": "boolean"
        },
        "createdAt": {
          "title": "Vehiculo.createdAt",
          "type": "string"
        }
      },
      "required": [
        "todosId",
        "title",
        "description",
        "status",
        "createdAt"
      ],
      "additionalProperties": false,
      "title": "Vehiculo",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};